name: tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Disable etelemetry
      run:  echo "NO_ET=TRUE" >> $GITHUB_ENV

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libxslt-dev git dcmtk

    - name: Update build tools
      run: python -m pip install --upgrade pip

    - name: Install XNAT checks
      run: python -m pip install .[test]

    - name: Save XNAT username/password in ~/.netrc
      run: |
        echo "machine localhost:8080" > $HOME/.netrc
        echo "user admin" >> $HOME/.netrc
        echo "password admin" >> $HOME/.netrc
    - name: Pytest
      run: pytest -vvs --cov xnat_ingest --cov-config .coveragerc --cov-report xml .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
